--- #YAML:1.0
name:               XML-QOFQSF
version:            0.05
abstract:           convert personal data to and from QSF XML files
author:
    - Neil Williams <codehelp@debian.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::Struct:     0
    Data::Random:      0
    Date::Format:      0
    Date::Parse:       0
    Test::More:        0
    XML::LibXML::SAX:  0
    XML::Simple:       0
    XML::Writer:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
