# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-QOFQSF
version:      0.04
version_from: lib/XML/QOFQSF.pm
installdirs:  site
requires:
    Class::Struct:                 0
    Data::Random:                  0
    Date::Format:                  0
    Date::Parse:                   0
    Test::More:                    0
    XML::Simple:                   0
    XML::Writer:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
